{{-- {{ dd(session($key)) }} --}}

@php
    if (session($key) != null) {
        $payload = session($key);
        // session()->pull($key);
    } else {
        abort('403', 'Unauthorized or session expired.');
    }
@endphp

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Report Template</title>

    @vite('resources/css/app.css')
</head>
<body class="antialiased flex flex-col h-screen  text-sm font-sans text-gray-700 tracking-tight">
    <div class="w-full bg-gradient-to-t from-slate-200 via-white">
        <div class="container flex justify-between w-full mx-auto p-8">
            <div class="flex flex-col justify-between w-5/12">
                <div class="mb-2">
                    <svg width="80" height="80" viewBox="0 0 24 24" fill="#4f46e5" xmlns="http://www.w3.org/2000/svg" class="text-primary fill-current">
                        <path d="M13 2L3 14H11L9 22L21 10H13L15 2Z" />
                    </svg>

                </div>

                <div class="flex flex-col gap-y-4">
                    <span class="flex flex-col font-bold">
                        <span class="text-base">{{ $payload['name'] ?? 'Report' }}</span>
                        <span class="font-normal text-[10px] text-gray-500">PCS Transaction Logs</span>
                    </span>
                </div>
            </div>

            <div class="flex flex-col justify-between text-[10px]">
                <div class="flex">
                    <span class="font-light">Date Generate: {{ now()->format('l, F j, Y') }}</span>
                </div>

                <div class="flex flex-col">
                    @if ($payload['user_id'] != 0)
                        <p>Transaction Logs of {{ $payload['user'][0]->name }}</p>
                    @endif
                    <p>Report Generated By: {{ auth()->user()->name }}</p>
                </div>
            </div>
        </div>
    </div>

    {{-- SVG Charts --}}
    {{-- <div class="container mx-auto my-8">
        <div class="flex w-full">
            <div id="bar-container" class="w-full"></div>
            <div id="pie-container" class="w-full"></div>
        </div>
    </div> --}}

    <div class="container mx-auto p-8">
        <table class="border-collapse w-full text-[12px]">
            <thead>
                <tr class="text-left">
                    @if ($payload['user_id'] == 0)
                    <th class="pb-2">Name</th>
                    @endif
                    <th class="pb-2">Date In</th>
                    <th class="pb-2">Time In</th>
                    <th class="pb-2">Date Out</th>
                    <th class="px-0 pb-2">Time Out</th>
                    <th class="px-0 pb-2">Purpose</th>
                    <th class="px-0 pb-2">IP Address</th>
                </tr>
            </thead>
            <tbody class="divide-y divide-gray-200">
                @foreach ($payload['query'] as $data)
                    <tr>
                        @if ($payload['user_id'] == 0)
                        <td class="py-1">{{ $data->users->name }}</td>
                        @endif
                        <td class="py-1">{{ $data->date_in }}</td>
                        <td class="py-1">{{ $data->time_in }}</td>
                        <td class="py-1">{{ $data->date_out }}</td>
                        <td class="py-1">{{ $data->time_out }}</td>
                        <td class="py-1">{{ $data->purposes->name }}</td>
                        <td class="py-1">{{ $data->users->identifiers[0]->ip_address ?? '' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="container mx-auto p-8">
        <div class="border-t border-gray-300 pt-6 text-center">
            <p class="mb-12 italic">This report was system-generated and does not require a signature.</p>

            <div class="flex justify-between items-center px-16 mt-16">
                <div class="text-center">
                    <div class="border-t-2 border-gray-700 w-48 mx-auto"></div>
                    <p class="mt-2">Prepared by</p>
                    <p class="mt-2">{{ auth()->user()->name }}</p>
                </div>

                <div class="text-center">
                    <div class="border-t-2 border-gray-700 w-48 mx-auto"></div>
                    <p class="mt-2">Approved by</p>
                    <p class="mt-2"></p>
                </div>
            </div>
        </div>
    </div>

    {{-- Highcharts.js Library --}}
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script type="text/javascript">
        Highcharts.chart('bar-container', {
            chart: {
                type: 'column'
            },
            title: {
                text: 'Best Selling Products',
                align: 'left'
            },
            xAxis: {
                categories: [2021, 2022, 2023, 2024],
                crosshair: true,
                accessibility: {
                    description: 'Consumer Electronics'
                }
            },
            yAxis: {
                min: 0,
                title: {
                    text: 'Number of units sold'
                }
            },
            plotOptions: {
                animation: {
                    duration: 0
                },
                column: {
                    animation: {
                        duration: 0
                    },
                    pointPadding: 0.1,
                    borderWidth: 0
                }
            },
            series: [
                {
                    name: 'Phones',
                    data: [56, 12, 33, 65]
                },
                {
                    name: 'Laptop',
                    data: [77, 56, 23, 66]
                },
                {
                    name: 'Desktop',
                    data: [66, 42, 91, 55]
                },
            ]
        });

        Highcharts.chart('pie-container', {
            chart: {
                type: 'pie'
            },
            title: {
                text: 'Mobile Devices Market Share'
            },
            tooltip: {
                valueSuffix: '%'
            },
            plotOptions: {
                animation: {
                    duration: 0
                },
                series: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: [{
                        enabled: true,
                        distance: 20
                    }, {
                        enabled: true,
                        distance: -40,
                        format: '{point.percentage:.1f}%',
                        style: {
                            fontSize: '1.2em',
                            textOutline: 'none',
                            opacity: 0.7
                        },
                        filter: {
                            operator: '>',
                            property: 'percentage',
                            value: 10
                        }
                    }]
                }
            },
            series: [
                {
                    name: 'Percentage',
                    colorByPoint: true,
                    animation: {
                        duration: 0
                    },
                    data: [
                        {
                            name: 'Phones',
                            y: 55.02,
                            sliced: true,
                            selected: false,
                        },
                        {
                            name: 'Tablets',
                            sliced: true,
                            selected: false,
                            y: 26.71
                        },
                        {
                            name: 'Laptops',
                            y: 15.5,
                            sliced: true,
                            selected: false,
                        },
                    ]
                }
            ]
        });
    </script>
</body>
</html>
